#!/bin/bash
set -e

NFS_SERVER=backupstore_nfs_test_server
NFS_PATH="/opt/backupstore"

function cleanup {
        echo Stopping NFS server
        docker rm -vf $NFS_SERVER
}
trap cleanup EXIT

cd $(dirname $0)/..

echo Starting NFS server

docker run -d --name $NFS_SERVER --net container:$(hostname) --privileged docker.io/erezhorev/dockerized_nfs_server $NFS_PATH

echo Running tests

PACKAGES="$(find -name '*.go' | xargs -I{} dirname {} |  cut -f2 -d/ | sort -u | grep -Ev '(^\.$|.git|.trash-cache|vendor|bin)' | sed -e 's!^!./!' -e 's!$!/...!')"

go test -race -cover ${PACKAGES}

