name: Codespell

on:
  pull_request:
    branches:
    - master
    - main
    - "v*.*.*"

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      with:
        fetch-depth: 1
    - name: Check code spell
      uses: codespell-project/actions-codespell@8f01853be192eb0f849a5c7d721450e7a467c579 # v2
      with:
        check_filenames: true
        skip: "*/**.yaml,*/**.yml,./scripts,./vendor,MAINTAINERS,LICENSE,go.mod,go.sum"
